---
- name: Deploy root dotfiles
  hosts: localhost
  connection: local
  become: true
  become_user: root
  gather_facts: true
  vars:
    target_home: /root
    target_user: root
    target_group: root
    is_root: true
  roles:
    - emacs
    - dotfiles
