---
- name: Deploy user dotfiles
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    target_home: "{{ ansible_env.HOME }}"
    target_user: "{{ ansible_user_id }}"
    target_group: "{{ ansible_user_id }}"
    is_root: false
  roles:
    - dotfiles
    - emacs
    - zsh
